# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-vpc-flow-logs-bucket
  description: This component is responsible for provisioning an encrypted S3 bucket which is configured to receive VPC Flow Logs
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component






